import Head from "next/head";
import Link from "next/link";
import Circle from "public/images/circle-accent-1.svg";
import Header from "src/pages/parts/Header";
import Hero from "src/pages/parts/Hero";
import Clients from "src/pages/parts/Clients";
import ListCourses from "src/pages/parts/ListCourses";
import axios from "src/configs/axios";
import ListCategories from "src/pages/parts/ListCategories";
import Footer from "src/pages/parts/Footer";
import courses from "src/constants/api/courses";

function Home({ data }) {
  return (
    <>
      <Head>
        <title>Esploor</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <section className="header-clipping pt-10">
          <Circle className="absolute left-0 bottom-0"></Circle>
          <div className="sunshine"></div>
          <div className="container mx-auto">
            <Header></Header>
            <Hero></Hero>
          </div>
        </section>
        <section className="container mx-auto pt-24">
          <Clients></Clients>
        </section>
        <section className="container mx-auto pt-24">
          <ListCourses data={data}></ListCourses>
        </section>
        <div className="container mx-auto pt-24">
          <ListCategories></ListCategories>
        </div>
        <div className="mt-24 bg-indigo-1000 py-12">
          <Footer></Footer>
        </div>
      </main>
    </>
  );
}

Home.getInitialProps = async () => {
  try {
    const data = await courses.all();
    return { data: data.data };
  } catch (error) {
    return error;
  }
};
export default Home;
