import Head from "next/head";

export default function Home() {
  return (
    <div className="container text-red-800 mx-auto mt-4">
      <Head>
        <title>Esploor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Halaman Utama</h1>
      </main>
    </div>
  );
}
